### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by Kralizek** [RaJiska/terraform-aws-fck-nat#3]
Hi,

Thank you for this project. I arrived here from a link in a issue in the fck-nat repository.

I was wondering if this is ok to deploy or is it still at a development stage.

I'm not asking if it's production grade. I'm working on a personal project and the managed NAT cost is not sustainable. Most likely I'll switch back to the managed NAT by the time/if I hit production.

So I just need this to be stable enough not to think about it.

Thanks =)

**Comment by RaJiska** [comment]
Oops, it's me, I think I read to hastily, no offense taken!

As for the quality of the project, I consider it to be both a development and production grade. There is one detail that might bother you, it's [route_table_id](https://github.com/RaJiska/terraform-aws-fck-nat#input_route_table_id), which currently supports only one route table, while in theory a NAT instance use may span over multiple subnets, I covered it in this issue [route_table_id](https://github.com/RaJiska/terraform-aws-fck-nat#input_route_table_id). This is on my todo list.

Other than that I have tested it extensively and everything worked as expected, and if not feel free to open an issue to report it and I'd be happy to look into it !

**Comment by Kralizek** [comment]
One question. Right now I'm using the cloudposse module "dynamic_subnets". Any idea how the two things go together?

```terraform
module "subnets" {
  source  = "cloudposse/dynamic-subnets/aws"
  version = "2.4.1"

  availability_zones   = var.availability_zones
  vpc_id               = aws_vpc.default.id
  igw_id               = [aws_internet_gateway.default.id]
  ipv4_cidr_block      = [aws_vpc.default.cidr_block]
  nat_gateway_enabled  = true
  nat_instance_enabled = false
}
```

**Comment by RaJiska** [comment]
Hello!

In regards of SSH, I am waiting for the PR https://github.com/AndrewGuenther/fck-nat/pull/48 to be approved as it also has an impact on SSH, and I'd have wished to do a single PR here that adds all the configuration at once for SSH configuration.

Disabling the default security group as well as supplying additional security groups is a planned feature.

**Comment by Kralizek** [comment]
Given that instances can have more than one sg, you can just get a list of IDs to append 🤔

**Comment by RaJiska** [comment]
Yes, in my last sentence, one does not exclude the other :)
