### ISSUE TITLE
Compatibilty with cloudposse

### ISSUE THREAD

**Issue by cannonkalra** [RaJiska/terraform-aws-fck-nat#31]
is it possible to make it compatible with [cloudposse/terraform-aws-dynamic-subnets](https://github.com/cloudposse/terraform-aws-dynamic-subnets)

**Comment by RaJiska** [comment]
Which part should be compatible ? I am not familiar with this module but from what I can see they use their own NAT instance.

If you only want to manage a single module then it's up to them to do the change to their module.
If you are OK with managing multiple modules you may want to simply disable the NAT feature from this module and configure fck-nat module using the output of the cloudposse module.

**Comment by cannonkalra** [comment]
I was trying to make this work, figured out needed to disable `ebs_optimisation` for the ec2 which is enabled by default in the **cloudposse** dynamic subnets module.. 

[https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/213](https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/213)

closing the issue, it wasn't a problem with `fck-nat`, just using the AMI with EBS Opimisation Off fixed the problem
