### ISSUE TITLE
inline_policy argument is deprecated

### ISSUE THREAD

**Issue by bobsut** [RaJiska/terraform-aws-fck-nat#41]
on `../../iam.tf` line 118, in resource "aws_iam_role"

The `inline_policy` argument is deprecated. Use the `aws_iam_role_policy` resource instead.

**Comment by RaJiska** [comment]
Looks like [a recent update](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.68.0) to the provider deprecated the `inline_policy` argument. Thank you for making a PR to address this.

**Comment by RaJiska** [comment]
Merged the PR!

**Comment by saqib-ahmed** [comment]
@RaJiska, I see the PR merged, but you haven't released this to the Terraform registry yet. Can you please release this feature? It is bugging our terraform runs.

Thanks.
