### ISSUE TITLE
Attaching the same elastic IP not working

### ISSUE THREAD

**Issue by hrist0stoichev** [RaJiska/terraform-aws-fck-nat#5]
Hello and thank you for developing this module! I'm trying to pass `eip_allocation_ids` so that the NAT instance always has the same public IP but it's not working. I don't see the elastic IPs being associated with the EC2 instances. Here's an example configuration:

```
resource "aws_eip" "nat" {
  count = length(var.external_subnets)
  vpc   = true
}

module "fck-nat" {
  count = length(var.external_subnets)

  source  = "RaJiska/fck-nat/aws"
  version = "1.2.0"

  name                 = "fck-nat-${count.index}"
  vpc_id               = aws_vpc.main.id
  subnet_id            = element(aws_subnet.external.*.id, count.index)
  
  ami_id               = "ami-00d653f185e930c04"
  instance_type        = "t4g.nano"
  use_spot_instances   = false
  use_cloudwatch_agent = true
  encryption           = true
  update_route_table   = true
  route_table_id       = element(aws_route_table.internal.*.id, count.index)
  ha_mode              = true
  eip_allocation_ids   = [element(aws_eip.nat.*.id, count.index)]
}
```

I see that the `allocation_id` is passed in the user data as `eip_id=...` but for some reason it is not associated with the EC2 as it should be happening [here](https://github.com/AndrewGuenther/fck-nat/blob/main/service/fck-nat.sh#L18). I tried viewing logs from inside the instance with `aws ec2 get-console-output --instance-id ...` but didn't have much success as no logs were shown. I'm wondering whether I need to change my configuration to something like
```
resource "aws_eip" "nat" {
  count = length(var.external_subnets)
  vpc   = true
  network_interface = element(fck-nat.*.eni_id, count.index)
}
```
which would associate the Elastic IP with the Network Interface but then I'm not sure why [this](https://github.com/AndrewGuenther/fck-nat/blob/main/service/fck-nat.sh#L18) call should be made at all. As a matter of fact, I'm also wondering about [those calls](https://github.com/AndrewGuenther/fck-nat/blob/a07a64dd7a52090648e98875dc8aea8121fdf209/service/fck-nat.sh#L31-L43) as well since the network interface is already attached to the EC2. Maybe there's no need to pass `eni_id` and `eip_id` if the infrastructure is already configured (eip and eni attached)? That would also remove the need for the IAM permissions.

Another eip related thing I'm wondering about is [this one](https://github.com/RaJiska/terraform-aws-fck-nat/blob/6c05cba132341a7f995deb3e6c37ccbabf0938fc/ec2.tf#L54-L59). Do you think that if `eip_allocation_ids` is provided there's no need to create an ephemeral public network interface since there's already an elastic IP that will be associated with this instance?

**Comment by hrist0stoichev** [comment]
> Which AMI are you using for this ? Please beware that as stated in the README file, some of the features provided by this terraform module are not fully released yet in the fck-nat project. This means that to be able to use them, you'd need to build the fck-nat image yourself from the latest commit.

I was using the lates publicly available AMI but after your comment I decided to build one myself and now the eip assignment seems to be working just fine. It's pretty annoying that the latest publicly available AMI is based on a version that lacks functionalities clearly described in the documentation without anything being mentioned about that. I am actually glad that I decided to open the issue, otherwise if you hadn't told me about this I might have still be trying to look for the problem elsewhere. So, thank you!

Here's some help for the people trying to build their own AMI on MacOS as, again, it's not clearly described in the documentation:
```
# Only set those 2 variables, everything else can be copy pasted
V=1.2.3-whatever        # the version to build
R=eu-west-2             # where to push the AMI to

git clone https://github.com/AndrewGuenther/fck-nat.git
cd fck-nat

cat << EOF > packer/my-vars.pkrvars.hcl
architecture = "arm64"
version = $V
region = $R
EOF

brew install packer
packer init ./packer/fck-nat.pkr.hcl

docker run -w /src -v $(pwd):/src kong/fpm make VERSION=$V package
packer build -var-file="./packer/my-vars.pkrvars.hcl" ./packer/fck-nat.pkr.hcl
```

**Comment by hrist0stoichev** [comment]
Thank you! 🙇

**Comment by RaJiska** [comment]
Hey @hrist0stoichev ,

Follow up regarding your earlier concern with documentation including unreleased features. Your suggestion has been brought up and the owner of the project has updated to include [versioned documentation](https://fck-nat.dev/develop/). This should make it less confusing for people working with this project in the future.

**Comment by hrist0stoichev** [comment]
That's great news! I hope less people have troubles running fck-nat this way!
