### ISSUE TITLE
The repository doesn't match the existing Terraform module

### ISSUE THREAD

**Issue by RohanDey02** [RaJiska/terraform-aws-fck-nat#6]
@RaJiska, the repository shows use of multiple route tables using route_tables_id (what I wish to use), but the [Terraform module](https://registry.terraform.io/modules/RaJiska/fck-nat/aws/1.2.0?utm_content=documentLink&utm_medium=Visual+Studio+Code&utm_source=terraform-ls
) is still using the deprecated version.

When will this be updated?

**Comment by RaJiska** [comment]
Yes, if you are using `main` branch it will show the documentation as updated for this branch. The multiple route tables will come in a future release. You may want to instantiate your Terraform module with the Git repository to latest version.
