### ISSUE TITLE
Allow to use non-arm instances

### ISSUE THREAD

**Issue by oleksii-kalinin** [RaJiska/terraform-aws-fck-nat#7]
Hi. I'm trying to run this module with t2.micro, and I can't use it b/c of the wrong (?) arm regex checker. I'm not a master of regex, but for me, it looks a little bit wrong. I was trying to use regex101 but found redundant backslashes.
`[a-zA-Z]+\\d+g[a-z]*\\..+` should be `[a-zA-Z]+\d+g[a-z]*\..+`

```
╷
│ Error: Error in function call
│
│   on .terraform/modules/fck-nat/main.tf line 2, in locals:
│    2:   is_arm             = regex("[a-zA-Z]+\\d+g[a-z]*\\..+", var.instance_type) == var.instance_type
│     ├────────────────
│     │ while calling regex(pattern, string)
│     │ var.instance_type is "t2.micro"
│
│ Call to function "regex" failed: pattern did not match any part of the given string.
```

**Comment by RaJiska** [comment]
Hi, I'm away for now so I won't be able to debug this. As for your comment on the regex itself, double backslash is needed to escape the backslash itself for Terraform.

To make it work you might want to try t4g instances which are cheaper than T2 (T3 is actually cheaper than T2 as well), you'd run ARM though.

**Comment by oleksii-kalinin** [comment]
Yeah, it's cheaper but not free (for free-tier).
